<a href="https://colab.research.google.com/github/tvdiepcs/ReadInVietnamese/blob/master/PLA_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
def predict(w,X):
  """
  predict label of each row of X, given w
  X: a 2-d numpy array of shape(N,d), each row is a datapoint
  w: a 1-d numpy array of shape(d)
  """
  return np.sign(X.dot(w))

In [0]:
def perceptron(X,y,w_init):
  """perform perceptron learning algorithm
  X: a 2-d numpy array of shape(N,d), each row is a datapoint
  Y: a 1-d numpy array of shape(N), label of each row of X.y[i]=1/-1
  w_init: a 1-d numpy array of shape(d)
  """
  w=w_init
  while(True):
    pred=predict(w,X)
    #find indexes of misclassified points
    mis_indxs=np.where(np.equal(pred,y)==False)[0]
    print(np.where(np.equal(pred,y)==False))
    print(mis_indxs)
    #number of indexes of misclassified points
    num_mis=mis_indxs.shape[0]
    if num_mis==0: #no more misclassified point
      return w
    random_id=np.random.choice(mis_indxs,1)[0]
    #update w
    w=w+y[random_id]*X[random_id]
  return w

In [0]:
mean=[[-1,0],[1,0]]
cov=[[.3,.2],[.2,.3]]
N=10
X0=np.random.multivariate_normal(mean[0],cov,N)
X1=np.random.multivariate_normal(mean[1],cov,N)
X=np.concatenate((X0,X1),axis=0)
y=np.concatenate((np.ones(N),-1*np.ones(N)))

Xbar=np.concatenate((np.ones((2*N,1)), X), axis=1)
w_init=np.random.randn(Xbar.shape[1])
w=perceptron(Xbar,y,w_init)

(array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19]),)
[ 0  1  2  3  4  5  7  8  9 10 11 12 13 14 15 16 17 18 19]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 14, 15, 16, 17, 18]),)
[ 0  1  2  3  4  5  6  7  8  9 11 12 14 15 16 17 18]
(array([10, 13, 16, 19]),)
[10 13 16 19]
(array([], dtype=int64),)
[]


In [0]:
print(w)

[ 0.04913276 -2.56462026  2.14268333]


In [0]:
arr=np.array([1,1,-1,1,-1,-1])
arr1=np.array([-1,-1,1,1,1,-1])

print(np.where(np.equal(arr,arr1)==True)[0])

[3 5]
